image: docker:stable
services:
  - docker:dind

variables:
  APP: spa-frontend

stages:
  - test
  - build
  - push
  - review
  - staging
  - prod

### testing test pipeline for merge request
test:
  stage: test
  image: node:latest
  script:
    - make build
  only:
    - merge-requests

### building
build:
  stage: build
  image: node:latest
  script:
    - make build
  artifacts:
    paths:
      - dist/
    expire_in: 1 day
  only:
    variables:
      - $CI_COMMIT_TAG =~ /^v\d.*/
      - $CI_COMMIT_REF_NAME =~ /^review\/.*$/


### pushing image
push release:
  stage: push
  before_script:
    - apk add --no-cache make git
  script:
    - make build-image
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - make push
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /^v\d.*/

push review:
  stage: push
  variables:
    NAMESPACE: $CI_COMMIT_REF_SLUG
  before_script:
    - apk add --no-cache make git
  script:
    - make build-image
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - make push
  only:
    refs:
      - branches
    variables:
      - $CI_COMMIT_REF_NAME =~ /^review\/.*$/


### deploying...
deploy prod:
  stage: prod
  image: ${CI_REGISTRY}/dantser/auto/deploy-image
  script:
    - make deploy
  environment:
    name: prod
  when: manual
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /^v\d.*/

deploy staging:
  stage: staging
  image: ${CI_REGISTRY}/dantser/auto/deploy-image
  variables:
    NAMESPACE: staging
  script:
    - make deploy
  environment:
    name: staging
  only:
    refs:
      - tags
    variables:
      - $CI_COMMIT_TAG =~ /^v\d.*/

deploy review:
  stage: review
  image: ${CI_REGISTRY}/dantser/auto/deploy-image
  variables:
    NAMESPACE: $CI_COMMIT_REF_SLUG
  script:
    - make deploy
  environment:
    name: $CI_COMMIT_REF_NAME
    on_stop: 'stop review'
  only:
    refs:
      - branches
    variables:
      - $CI_COMMIT_REF_NAME =~ /^review\/.*$/

stop review:
  stage: review
  image: ${CI_REGISTRY}/dantser/auto/deploy-image
  variables:
    GIT_STRATEGY: none
    NAMESPACE: $CI_COMMIT_REF_SLUG
  script:
    - helm delete --purge ${APP}-${NAMESPACE}
    - danctl close-ns $NAMESPACE
  when: manual
  environment:
    name: $CI_COMMIT_REF_NAME
    action: stop
  only:
    refs:
      - branches
    variables:
      - $CI_COMMIT_REF_NAME =~ /^review\/.*$/
