apiVersion: v1
kind: Service
metadata:
  name: {{ template "name" . }}
  labels:
    app: {{ template "name" . }}
    chart: '{{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_"  }}'
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.externalPort }}
      targetPort: {{ .Values.service.internalPort }}
      protocol: TCP
      name: {{ template "name" . }}
  selector:
    app: {{ template "name" . }}
    release: {{ .Release.Name }}
