/**
 * API module
 * BPM Indicator State API
 */
import { ApiModule } from '@/api/api-module'
import routes from './routes'
import uuidv4 from 'uuid/v4'

export class ApiIndicatorState extends ApiModule {

  list( processId, indicatorId ) {
    return new Promise((resolve, reject) => {
      let apiPath = routes.state.index.replace("{model_id}", processId).replace("{indicator_id}", indicatorId)

      this.http.get(apiPath).then(response => {
        // console.log("IndicatorState API, 'list' action, server response:")
        // console.log(response)

        if (response.status == 200 && response.data && response.data.list) {
          resolve( response.data.list )
        } else {
          reject("Error occurres while loading data from server")
        }
      }).catch(error => {
        reject(error)
      })
    })
  }

  item( processId, indicatorId, id ) {
    return new Promise((resolve, reject) => {
      let apiPath = routes.state.show.replace("{model_id}", processId).replace("{indicator_id}", indicatorId).replace("{state_id}", id)

      this.http.get(apiPath).then(response => {
        // TODO - need to check server response
        // console.log("IndicatorState API, GET 'item', server response:")
        // console.log(response)

        if (response.status == 200 && response.data && response.data.item) {
          resolve( response.data.item )
        } else {
          reject("Error occurres while loading data from server")
        }
      }).catch(error => {
        reject(error)
      })
    })
  }

  create( processId, indicatorId, data ) {
    return new Promise((resolve, reject) => {
      if (processId && indicatorId && data) {
        let apiPath = routes.state.create.replace("{model_id}", processId).replace("{indicator_id}", indicatorId)

        // Generate ID for a new item.
        if (typeof data.id === 'undefined' || !data.id) {
          data.id = uuidv4()
        }

        this.http.put(apiPath, data).then(response => {
          // console.log("IndicatorState API, 'create', server response:")
          // console.log(response)

          if (response.status == 201) {
            // Fill ID property if it was generated by server.
            if (typeof data.id === 'undefined' && response.data && response.data.id) {
              data.id = response.data.id
            }

            resolve( data )
          } else {
            reject("Error occurres while updating PORT data.")
          }
        }).catch(error => {
          reject(error)
        })
      }
    })
  }

  update( processId, indicatorId, id, data ) {
    return new Promise((resolve, reject) => {
      if (processId && indicatorId && id) {
        let apiPath = routes.state.update.replace("{model_id}", processId).replace("{indicator_id}", indicatorId).replace("{state_id}", id)

        this.http.patch(apiPath, data).then(response => {
          // console.log("IndicatorState API, 'update', server response:")
          // console.log(response)

          if (response.status == 200) {
            resolve( data )
          } else {
            reject("Error occurres while updating PORT data.")
          }
        }).catch(error => {
          reject(error)
        })
      }
    })
  }

  delete( processId, indicatorId, id ) {
    return new Promise((resolve, reject) => {
      if (processId && indicatorId && id) {
        let apiPath = routes.state.delete.replace("{model_id}", processId).replace("{indicator_id}", indicatorId).replace("{state_id}", id)

        this.http.delete(apiPath).then(response => {
          // console.log("IndicatorState API, 'delete', server response:")
          // console.log(response)

          if (response.status == 200) {
            resolve( true )
          } else {
            reject("Error occurres while deleting PORT data.")
          }
        }).catch(error => {
          reject(error)
        })
      }
    })
  }
}

// Create and export module class instance.
const apiIndicatorState = new ApiIndicatorState('indicatorState')
export default apiIndicatorState
