/**
 * API module
 * BPM Execution API
 */
import { ApiModule } from '@/api/api-module'
import routes from './routes'
import uuidv4 from 'uuid/v4'

export class ApiExecution extends ApiModule {

  list( processId, role ) {
    return new Promise((resolve, reject) => {
      let apiPath = routes.index.replace("{model_id}", processId)

      this.http.get(apiPath, {
        params: { role }
      }).then(response => {
        // console.log("Execution API, 'list' action, server response:")
        // console.log(response)

        // if (response.status == 200 && response.data && response.data.list) {
        //   resolve( response.data.list )
        if (response.status == 200 && response.data) {
          resolve( response.data )
        } else {
          reject("Error occurres while loading data from server")
        }
      }).catch(error => {
        reject(error)
      })
    })
  }

  item( processId, id ) {
    return new Promise((resolve, reject) => {
      let apiPath = routes.show.replace("{model_id}", processId).replace("{contractor_id}", id)

      this.http.get(apiPath).then(response => {
        // TODO - need to check server response
        // console.log("Execution API, GET 'item', server response:")
        // console.log(response)

        if (response.status == 200 && response.data && response.data.item) {
          resolve( response.data.item )
        } else {
          reject("Error occurres while loading data from server")
        }
      }).catch(error => {
        reject(error)
      })
    })
  }

  create( processId, data ) {
    return new Promise((resolve, reject) => {
      if (processId && data) {
        let apiPath = routes.create.replace("{model_id}", processId)

        // Generate ID for a new item.
        if (typeof data.id === 'undefined' || !data.id) {
          data.id = uuidv4()
        }

        this.http.put(apiPath, data).then(response => {
          // console.log("Execution API, 'create', server response:")
          // console.log(response)

          if (response.status == 201) {
            // Fill ID property if it was generated by server.
            if (typeof data.id === 'undefined' && response.data && response.data.id) {
              data.id = response.data.id
            }

            resolve( data )
          } else {
            reject("Error occurres while updating data.")
          }
        }).catch(error => {
          reject(error)
        })
      }
    })
  }

  update( processId, data ) {
    return new Promise((resolve, reject) => {
      // if (processId && id && data) {
      if (processId && data) {
        // let apiPath = routes.update.replace("{model_id}", processId).replace("{contractor_id}", id)
        let apiPath = routes.update.replace("{model_id}", processId)

        this.http.patch(apiPath, data).then(response => {
          // console.log("Execution API, 'update', server response:")
          // console.log(response)

          if (response.status == 200) {
            resolve( data )
          } else {
            reject("Error occurres while updating data.")
          }
        }).catch(error => {
          reject(error)
        })
      }
    })
  }

  delete( processId, id ) {
    return new Promise((resolve, reject) => {
      if (processId && id) {
        let apiPath = routes.delete.replace("{model_id}", processId).replace("{contractor_id}", id)

        this.http.delete(apiPath).then(response => {
          // console.log("Execution API, 'delete', server response:")
          // console.log(response)

          if (response.status == 200) {
            resolve( true )
          } else {
            reject("Error occurres while deleting data.")
          }
        }).catch(error => {
          reject(error)
        })
      }
    })
  }
}

// Create and export module class instance.
const apiExecution = new ApiExecution('execution')
export default apiExecution
